apiVersion: apps/v1
kind: Deployment
metadata:
  name: syntagmas
  namespace: linguist-system-backend
  labels:
    app: syntagmas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syntagmas
  template:
    metadata:
      labels:
        app: syntagmas
    spec:
      containers:
        - name: syntagmas-container
          image: syntagmas
          env:
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: rabbitmq_user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: rabbitmq_password
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: rabbitmq_host
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: rabbitmq_port
          resources:
            limits:
              memory: 500Mi
              cpu: 1
            requests:
              memory: 200Mi
              cpu: 1
          ports:
            - containerPort: 8078
      imagePullSecrets:
        - name: reg-sample