apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-completed-pods
  namespace: linguist-system-backend
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name:  linguist-kubectl
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - kubectl delete pod --field-selector=status.phase==Succeeded,status.phase==Failed
          restartPolicy: OnFailure