apiVersion: apps/v1
kind: Deployment
metadata:
  name: frequences
  namespace: linguist-system
  labels:
    app: frequences
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frequences
  template:
    metadata:
      labels:
        app: frequences
    spec:
      containers:
        - name: frequences-container
          image: frequences
          env:
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: rabbitmq_user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: rabbitmq_password
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: rabbitmq_host
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: rabbitmq_port
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: minio_access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: minio_secret_key
            - name: MINIO_HOST
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: minio_host
            - name: MINIO_PORT
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: minio_port
          resources:
            limits:
              memory: 1000Mi
              cpu: 1
            requests:
              memory: 500Mi
              cpu: 1
          ports:
            - containerPort: 8074
      imagePullSecrets:
        - name: reg-sample