apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-np
  namespace: linguist-system-backend
spec:
  podSelector:
    matchLabels:
      app: database
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: repository
  policyTypes:
  - Ingress