apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: linguist-system-backend
spec:
  storageClassName: "database"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi