apiVersion: apps/v1
kind: Deployment
metadata:
  name: markers
  namespace: linguist-system-backend
  labels:
    app: markers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: markers
  template:
    metadata:
      labels:
        app: markers
    spec:
      containers:
        - name: markers-container
          image: markers
          env:
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: rabbitmq_user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: rabbitmq_password
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: rabbitmq_host
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: rabbitmq_port
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: minio_access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: minio_secret_key
            - name: MINIO_HOST
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: minio_host
            - name: MINIO_PORT
              valueFrom:
                configMapKeyRef:
                  name: linguist-config
                  key: minio_port
          resources:
            limits:
              memory: 2000Mi
              cpu: 2
            requests:
              memory: 1000Mi
              cpu: 1
          ports:
            - containerPort: 8066
      imagePullSecrets:
        - name: reg-sample