apiVersion: v1
kind: Service
metadata:
  name: react-spa
  namespace: linguist-system-frontend
  labels:
    app: react-spa
spec:
  selector:
    app: react-spa
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000